# Generated by Django 3.2.7 on 2021-10-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=250)),
                ('merchant_code', models.CharField(max_length=25)),
                ('merchant_address', models.TextField()),
            ],
        ),
    ]
